# Generated by Django 5.1.5 on 2025-02-11 11:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('Web Development', 'Web Development'), ('Business Analytics', 'Business Analytics'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Other', 'Other')], default='Data Analytics', max_length=200)),
                ('phonenumber', models.IntegerField(unique=True)),
                ('alternatenumber', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('remarks', models.TextField(default='', max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Demo Done', 'Demo Done'), ('Registration Done', 'Registration Done'), ('Admission Confirmed', 'Admission Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('referer', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
            ],
        ),
    ]
