# Generated by Django 5.1.5 on 2025-02-18 12:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pro_app', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.BigIntegerField()),
                ('phonenumber', models.IntegerField()),
                ('bankname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('pannumber', models.CharField(max_length=50)),
                ('cancelled_cheque', models.ImageField(upload_to='cancelled_cheques/')),
                ('remarks', models.TextField(default='', max_length=300)),
                ('status', models.CharField(choices=[('Verification Pending', 'Verification Pending'), ('Verified', 'Verified'), ('Cancelled', 'Cancelled')], default='Verification Pending', max_length=50)),
                ('referer', models.CharField(default=django.contrib.auth.models.User, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='alternatenumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
