# Generated by Django 5.1.5 on 2025-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pro_app', '0003_withdraw_alter_students_alternatenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
