# Generated by Django 5.1.5 on 2025-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pro_app', '0004_withdraw_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='name',
        ),
    ]
