# Generated by Django 5.1.5 on 2025-02-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pro_app', '0005_remove_withdraw_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='cancelled_cheque',
            field=models.FileField(blank=True, null=True, upload_to='cancelled_cheques/'),
        ),
    ]
